### ISSUE TITLE
Error when trying to install a github enterprise repo

### ISSUE THREAD

**Issue by speigg** [Orbs/jspm-git#12]
```
     Looking up gatech:user/repo
     Creating registry cache...
     Downloading gatech:user/repo@0.0.10
Thu Jan 22 2015 00:25:28 GMT-0500 (EST): Error while cloning the git branch: 
Cloning into '/var/folders/tt/xxx/T/jspm-git-115022-30287-n66f5p'...


err  Error downloading gatech:user/repo
     Cloning into '/var/folders/tt/xxx/T/jspm-git-115022-30287-n66f5p'...
```

**Comment by subesokun** [comment]
Hi @speigg, do you get any error when trying to clone the repository directly via git?
```bash
git clone -b 0.0.10 --depth 1 --single-branch $BASEURL/user/repo
```
Where `$BASEURL` is the URL you've defined in your endpoint configuration (`~/.jspm/config`).

**Comment by speigg** [comment]
Almost. This works:
```
git clone -b v0.0.10 --single-branch  https://github.gatech.edu/user/repo
```
But this does not:
```
git clone -b v0.0.10 --depth 1  --single-branch  https://github.gatech.edu/user/repo
```
The problem seems to be the `--depth 1` option, which causes the process to get stuck at "Cloning into 'repo'...". No idea why this would happen.

**Comment by speigg** [comment]
Everything works without the `--depth 1` option, I just tested in my fork of jspm-git... works great!!

**Comment by subesokun** [comment]
Thank you very much for offering a patch for your issue! Glad to hear that this solved your issue. Really strange that git clone fails for your repository when using the `--depth` argument. Which version of Git are you using (and on which system)? Maybe this error could be also related to the Git repository itself, not sure.

Back then I've explicitly added `--depth` to speed up cloning in case of larger repositories as only one revision has to be pulled from the repository instead of the full history. Hence I would propose to add a flag into the endpoint configuration to be able to tell jspm-git not to optimize the the clone process via the `--depth` argument.

**Comment by speigg** [comment]
```console
$ git --version
git version 1.9.3 (Apple Git-50)
```

Running on Mac OS X Mavericks

**Comment by speigg** [comment]
A configuration option works too. It looks like I'm not the only one who has had this issue:

https://github.com/gogits/gogs/issues/236
https://github.com/jakubgarfield/Bonobo-Git-Server/issues/84

But apparently it's a problem with the git server that affects cloning over http(s):
https://github.com/CocoaPods/CocoaPods/issues/2481#issuecomment-57420352

Someone suggested that using `git` instead of `https` works, so I'll try that

**Comment by speigg** [comment]
I couldn't get it to work with `git://` at all, so for now I have to clone without the `--depth 1` parameter.  Can you make the `--depth 1` option opt-in rather than opt-out?

**Comment by subesokun** [comment]
Thanks a lot for your investigations! So it seems to be an issue with cloning via http(s) from the Github enterprise server. Have you tried already to [clone via 'ssh://' from Github enterprise](https://help.github.com/enterprise/11.10.340/user/articles/which-remote-url-should-i-use/)? Maybe in that case `--depth` will work.

If this git clone issue via http(s) would be a general issue of the Git server daemon then it would make sense to consider to opt-in this optimizations when cloning via http. But as this is only an issue of Github enterprise I prefer making it opt-out. Often package repositories have a very long history and pulling everything has a great impact on performance.

I made some small test with the bower-angular repository and if I clone with `--depth 1` it took ~9 seconds to clone this repository. When I've left it away it took me more than 3 minutes and downloaded more than 70MB of data. So I'd strongly suggest to use `--depth 1` whenever possible.

Also as @guybedford mentioned in https://github.com/jspm/github/issues/27, to get the full feature support for your Github enterprise server (e.g. dependency look-ahead which speeds up the time needed to fetch all dependencies) you would need to use the Github endpoint. Adding a configuration to switch between `github.com` or another configurable host name seems to be doable with little changes.

**Comment by speigg** [comment]
I haven't be abel to clone with `ssh://` either. I suppose you are right that opt-out is definitely better then, considering the huge difference for some repositories.

**Comment by subesokun** [comment]
Is it asking you for a password when cloning via `ssh://`? If so you might need to check if you've uploaded your `id_rsa.pub` key onto you Github Enterprise account. Otherwise it won't authenticate your session.

**Comment by speigg** [comment]
No, it just times out: can't connect to port 22. I don't think we have ssh setup for our Github Enterprise server. Not sure if its a general issue with Github Enterprise or just ours.

**Comment by subesokun** [comment]
I see, yes that could be possible that you explicitly have to activate the ssh support or maybe some port forwarding is missing. I hope that I can close this bug this weekend.
