### ISSUE TITLE
'endpoint' has been renamed to 'registry' in jspm 0.15.0

### ISSUE THREAD

**Issue by frankwallis** [Orbs/jspm-git#16]
see https://github.com/jspm/jspm-cli/releases/tag/0.15.0

**Comment by subesokun** [comment]
Hi @frankwallis, luckily this change is not a breaking one so jspm-git still works as expected. As soon as I've time I was planning to update the Wiki etc. to rename everything from `endpoint` to `registry`

**Comment by frankwallis** [comment]
you're quite right, thanks for updating the readme

**Comment by subesokun** [comment]
Sure, you're welcome and thanks for supporting jspm-git :) In the next release also the remaining left overs of ´endpoint` will be replaced.
