### ISSUE TITLE
jspm global install doesn't work.

### ISSUE THREAD

**Issue by ProggerPete** [Orbs/jspm-git#19]
I've followed the instructions in the readme to connect to a bitbucket git repo.

First I installed jspm-git globally:

npm install -g jspm-git

Then I created the bitbucket registry

jspm registry create bitbucket jspm-git

Then I went to my jspm project and attempted to do an install.

jspm install bitbucket:accountname/reponame

I get:

err  Error: Cannot find module 'jspm-git'
         at Function.Module._resolveFilename (module.js:336:15)
         at Function.Module._load (module.js:278:25)
         at Module.require (module.js:365:17)
         at require (module.js:384:17)

If in my jspm project I install it locally:

npm install jspm-git --save-dev

Then the install command works as expected.

I wouldn't expect to need a local install after doing a global install.

**Comment by subesokun** [comment]
Hi @ProggerPete, could it be that you've installed jspm locally as well? In that case it won't be possible to require the global jspm-git, it has to be locally installed as well. Following combinations are valid

* global jspm + global jspm-git - OK
* global jspm + local jspm-git - ERROR
* local jspm + local jspm-git - OK
* local jspm + global jspm-git - ERROR

I'll put them also into the README.

**Comment by ProggerPete** [comment]
Yep, that's it. I do have jspm installed locally for that project.
