### ISSUE TITLE
Where is the registry stored and how can I remove it?

### ISSUE THREAD

**Issue by nordisk** [Orbs/jspm-git#20]
Hi.
I installed a local registry in my project. Where can I find the registry and how can I remove it?

**Comment by subesokun** [comment]
Hi @nordisk :), you can find your jspm-git registry configuration on Linux Systems in your `~/.jspm/config` file and on Windows in your `%LOCALAPPDATA%/.jspm/config` file. Does this answer your question?

**Comment by nordisk** [comment]
I finally found out myself ^^
Thank you for the great module btw.

**Comment by sgwatgit** [comment]
@nordisk Since there isn't a command via the API to remove a registry item, could this information above be placed in the README?

**Comment by subesokun** [comment]
Merged :+1:
