### ISSUE TITLE
Issue with multiple jspm processes running concurrently

### ISSUE THREAD

**Issue by mmoss** [Orbs/jspm-git#23]
We're seeing an issue, where when multiple jspm processes are running concurrently, they appear to overwrite/loose the config. I'll investigate and try to file a PR, but here's the current error we're seeing intermittently:

```
err  Registry bitbucket not found.

err  Unable to load registry bitbucket
```

This appears to happen with any git endpoints, not *just* bitbucket. There's also no stack trace, or any other real info related...

The endpoint was/is setup prior to running JSPM using the following:
```
jspm config registries.bitbucket.baseurl git+ssh://git@bitbucket.org/
jspm config registries.bitbucket.handler jspm-git
```

**Comment by subesokun** [comment]
Hi @mmoss, thanks for reporting and investigating! How is your current configuration looking like?

**Comment by mmoss** [comment]
```
{
  "defaultTranspiler": "babel",
  "defaultRegistry": "jspm",
  "strictSSL": true,
  "registries": {
    "github": {
      "handler": "jspm-github",
      "remote": "https://github.jspm.io"
    },
    "npm": {
      "handler": "jspm-npm",
      "remote": "https://npm.jspm.io"
    },
    "jspm": {
      "handler": "jspm-registry",
      "remote": "https://registry.jspm.io"
    },
    "bitbucket": {
      "baseurl": "git+ssh://git@bitbucket.org/",
      "handler": "jspm-git"
    }
  }
}
```

**Comment by slahav** [comment]
Hi @mmoss, i just have this happen to me as well:

```
err  Registry bitbucket not found.

err  Unable to load registry bitbucket

```
were you able to resolve it?

**Comment by subesokun** [comment]
Sorry to hear that you're also facing this issue. Im not yet sure if it's a bug within jspm-git or jspm itself. I'll try to reproducd it in the next days an let you know when I better understand what's going wrong.

**Comment by mmoss** [comment]
My project ended up killing our multi-process workflow, so the issue is no longer a blocker for us...

**Comment by subesokun** [comment]
I wrote now a small bash script that runs two jspm installs in parallel and so far I've noticed some errors when syncing the jspm registries in parallel as well as when running jspm install. But so far it seems that these errors are not specially related to jspm-git.
Which OS are you using? The error that the registry couldn't be loaded I haven't experienced so far.

**Comment by subesokun** [comment]
Concurrent installations are not yet supported in jspm and there is now an open feature request regarding that.

Moving issue to https://github.com/jspm/jspm-cli/issues/1609

**Comment by webdobe** [comment]
jspm registry create bitbucket jspm-git
# baseurl: https://bitbucket.org/
