### ISSUE TITLE
Shell-escape user input

### ISSUE THREAD

**Issue by nateabele** [Orbs/jspm-git#27]
Hey, thanks a lot for your work on this. I recently installed it and configured Bitbucket per the readme, and got the following error when attempting to `jspm install` a private Bitbucket repo:

```bash
warn Error on lookup for bitbucket:foo/bar, retrying (1).
     Error: /bin/sh: -c: line 0: syntax error near unexpected token `)'
/bin/sh: -c: line 0: `git ls-remote  refs/tags/* refs/heads/*'
```

At a guess, I re-ran `jspm registry create bitbucket jspm-git` and wrapped my password in single-quotes, after which installing from Bitbucket worked normally. My password is randomly-generated and includes shell control characters, so it looks like lack of escaping is the problem. Based on the output and a cursory scan of the code, I'm blindly assuming that the issue is [somewhere in this vicinity](https://github.com/Orbs/jspm-git/blob/8eb9809807098c4e0937002e16588094f58edcff/git.js#L342).

Let me know if there's anything else I can do to help track it down.

**Comment by subesokun** [comment]
Hi @nateabele, thanks for reporting the issue! The url that gets generated which includes the credentials is URI encoded but it seems like the Git client still has some problems with it. I'll investigate the error and let you know.

**Comment by nateabele** [comment]
Yeah, `encodeURIComponent(')') => ')'`, so the characters are URL-safe, but not shell-safe. From the look of the error, `sh` is choking on [the command being passed to `exec()`](https://github.com/Orbs/jspm-git/blob/8eb9809807098c4e0937002e16588094f58edcff/exec-git.js#L83) before `git` itself is even invoked.

I could try writing up a unit test if you want. Where should it go? `test.js`?

**Comment by subesokun** [comment]
That'd be great if you could write a unit test for it! But sadly the `gulp test` task is currently not in use at all... something that have been already on my todo list for long time :(

**Comment by subesokun** [comment]
Ok I've included now a fix which solves the issue and I'll prepare soon a release.

**Comment by subesokun** [comment]
jspm-git v0.4.3 has been released :tada:
