### ISSUE TITLE
Beta: `files` / `jspm/files` have no effect

### ISSUE THREAD

**Issue by unional** [Orbs/jspm-git#33]
~~Don't know if the non-beta version also have this problem.~~
UPDATE: Confirm it only exists in beta.
At least not on jspm@0.16.26 + jspm-git@0.4.4

I have a package that has the following:
```js
// package.json
{
  "files": [
    "dist/",
    "typings.json"
  ],
  "jspm": {
    "files": [
      "dist/",
      "typings.json"
    ]
  }
}
```
When I install it, neither have effect and I still get the whole repo under `jspm_package/bit/<mypackage>/`.
(bit is the registry created with `jspm-git`)

**Comment by subesokun** [comment]
Hi @unional, as jspm-git downloads only the package but the post processing like filtering files is done by jspm you need to report your issue [there](https://github.com/jspm/jspm-cli).

As a small ceveat, using the `files` property will only safe some disc size but it won't make the download faster as first everything gets downloaded and then afterwards jspm removes the unneeded files. So if your goal was to improve download speed you should host your "dist" version of your package in a separate repo.

**Comment by subesokun** [comment]
Oh sorry just saw that you've created already an issue there. Closing this one here in favor of https://github.com/jspm/jspm-cli/issues/1699
