### ISSUE TITLE
Bitbucket projects support

### ISSUE THREAD

**Issue by thefabulousdev** [Orbs/jspm-git#34]
I am unable to install packages living inside a project, meaning the git uri has an extra path such as 
`git.something.org/scm/foc/something-validations-phones.git`

Is this supported?

**Comment by subesokun** [comment]
Hi @thefabulousdev, could you describe in a little more detail your use case? So far I'm not sure if I understood your question correctly. What do you mean exactly by extra path?

**Comment by thefabulousdev** [comment]
[Here](https://github.com/Orbs/jspm-git/blob/master/README.md#bitbucket) it's stated that after adding the custom registry, it should be used as 

```bash
$ jspm install bitbucket:accountname/reponame
```

However bitbucket has now introduced projects, which add an extra path to a git uri, so ends up being

```bash
$ jspm install bitbucket:projectname/accountname/reponame
```

is this supported? Perhaps I'm looking in the wrong place

**Comment by subesokun** [comment]
As the `projectname/accountname/reponame` string just gets appended to the base URL i.e. `https://bitbucket.org/` there shouldn't be any issue. So the composed URL would be `https://bitbucket.org/projectname/accountname/reponame.git`

**Comment by thefabulousdev** [comment]
Then it's on me.

Thanks!
