### ISSUE TITLE
Create a Git registry non interactively?

### ISSUE THREAD

**Issue by nguillaumin** [Orbs/jspm-git#35]
Hi,

Is there a way to create a registry without being prompted for the base URL? That would be very handy for CI systems, something like:

```
jspm registry create mygit jspm-git --baseurl ssh://git@myserver/
```

Should I report that on the `jspm-cli` project instead?

Thanks,

Nico

**Comment by nguillaumin** [comment]
Actually that also applies to other interactive settings (advanced config, credentials, etc.)

**Comment by nguillaumin** [comment]
I came across https://github.com/jspm/jspm-cli/blob/master/docs/registries.md#auto-configuring-registries which does what I want, so I'm closing this.

**Comment by subesokun** [comment]
Hi @nguillaumin, yep that would have been also my answer :)

**Comment by nguillaumin** [comment]
Thanks, I had it working before posting here actually, but I got confused by JSPM asking me to setup my GitHub credentials (as I hit the API rate limit), I thought that was `jspm-git` asking me to setup my Git credentials for the registry...

**Comment by PizzaPete** [comment]
Sorry for commenting on a closed issue and 9 months after the issue was reported.
I'm interested in the fix of @nguillaumin. I'm trying to configure a private repo on CI systems without being prompted of the repo details.

I've read the link to auto-configuring-registries, but I can't make up my mind how to include this in an init script. Can you provide me with an example?

**Comment by subesokun** [comment]
Hi @PizzaPete, you've once to configure jspm and then you can simply the export command. It will print you then for each config property an import command which you can copy paste 1:1 into you init bash script which you can then share with others who want the same config as you. Does this help?

**Comment by PizzaPete** [comment]
Hey @subesokun,

Thank you for your reply. I didn't knew it was that easy! Didn't get that from the readme. It work's fine now.
