### ISSUE TITLE
Install package from mygitlab, dependencies from npm

### ISSUE THREAD

**Issue by Pleasurazy** [Orbs/jspm-git#36]
Hi, how are you?

Our node.js team has sharing some packages in private gitlab on Intranet.

I am trying reuse their packages with config:

```
{
  ....
  "mygitlab": {
    "version": "1.0",
    "baseurl": "https://gitlab.example.com", // access via VPN
    "auth": "hhhhhhhhhhhhhhhhaaaaaaaaaaasssssssssshhhhhhhhh",
    "handler": "jspm-git"
  }
}
```

The sharing packages has dependencies which specified in `package.json` like this:

```
{
  "name:": "awesome-tool",
  "main": "./index.js",
  "dependencies": {
    "bytes": "^2.3.0",
    "some-base-tool": "git+ssh://git@gitlab.example.com:30022/packages/some-base-tool.git#v0.2.x",
  }
}
```

Now, if I do `jspm install mygitlab:packages/awesome-tool` will get

```
     Looking up mygitlab:packages/awesome-tool
     Updating registry cache...
     Looking up mygitlab:bytes

warn Error on lookup for mygitlab:bytes, retrying (1).
     Error: fatal: Authentication failed for '/'


warn Error on lookup for mygitlab:bytes, retrying (2).
     Error: fatal: Authentication failed for '/'


warn Error on lookup for mygitlab:bytes, retrying (3).
     Error: fatal: Authentication failed for '/'


warn Error on lookup for mygitlab:bytes
     Error: fatal: Authentication failed for '/'


err  Error looking up mygitlab:bytes.

warn Installation changes not saved.
```

How can I make it lookup to npm?

many thanks

![fe80fb6bb7bd2af0f5dac0992ec28c0ea3fcb3d1](https://cloud.githubusercontent.com/assets/1500206/14741069/536bcd76-08c6-11e6-8839-9556939daede.gif)

**Comment by subesokun** [comment]
Hi @Pleasurazy! Just write `bytes: "npm:bytes@^2.3.0"` in your dependencies and it's going to use the npm registry for resolving this package. Btw. dependencies like `git+ssh://git@gitlab.example.com:30022/packages /some-base-tool.git#v0.2.x` won't work with jspm. You'd need to write it as `some-base-tool: "mygitlab:packages/some-base-tool@^0.2.0"` or similar to that depending on how you configure your baseUrl of your `mygitlab` registry.

Probably it should look like 

```
{
  "name:": "awesome-tool",
  "main": "./index.js",
  "dependencies": {
    "bytes": "^2.3.0",
    "some-base-tool": "git+ssh://git@gitlab.example.com:30022/packages/some-base-tool.git#v0.2.x",
  },
  jspm: {
  "dependencies": {
    "bytes": "^2.3.0",
    "some-base-tool": "git+ssh://git@gitlab.example.com:30022/packages/some-base-tool.git#v0.2.x",
  }
  }
}
```

**Comment by Pleasurazy** [comment]
hello @subesokun 

actually `npm:bytes` and `some-base-tool` is not my dependency directly.

real dependency tree is:
MY_JSPM_WEB_PROJECT <kbd><=</kbd> `mygitlab:awesome-tool` <kbd><=</kbd> (`npm:bytes` <kbd>+</kbd> `ssh//some-base-tool`)

I just trying resolve this problem in various ways. And jspm-git looks graceful.

I try to draw a mock to describe my situation:

![image](https://cloud.githubusercontent.com/assets/1500206/14760292/ab0654fa-0972-11e6-9577-b890325daf20.png)

Thank you for your quickly replied.

**Comment by subesokun** [comment]
OK I see. That's a bit tricky situation. If the awesome-tool package depends on native NPM functions i.e. if it requires some native NPM module then you can't use jspm-git. In that case you can install this package only via the jspm-npm. Does this awesome-tool package gets somehow provided in a private npm registry? If so you could install it via jspm-npm by setting the NPM registry globally or locally in your project via a .npmrc file. If awesome-tool tool uses only plain JS then using jspm-git is ok but you've to provide a package override configuration if that package isn't under your control, see https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm . if you need help on that please feel free to ask.

**Comment by Pleasurazy** [comment]
> If awesome-tool tool uses only plain JS then using jspm-git is ok but you've to provide a package override configuration if that package isn't under your control

Yes, awesome-tool tool just only plain JS, therefore it can be serve to browser.

I am successful installed using `-o '{"dependencies": {"bytes": "npm:bytes@^2", "debug": "npm:debug@^2", ...etc}}'`

and successful installed if I can control that package: 

```
{
  "name": "awesome-tool",
  "version": "1.0.0",
  "dependencies": {
    "bytes": "^2.3.0",
    "debug": "^2.2.0"
  },
  "jspm": {
    "dependencies": {
      "bytes": "npm:bytes@^2.3.0",
      "debug": "npm:debug@^2.2.0"
    }
  }
}
```

however, that is not graceful. I will continue work for graceful solution. thank you for your support. :)

> Does this awesome-tool package gets somehow provided in a private npm registry?

Not provided, since we are disallowing to publish packages to npm registry and any third party host.

**Comment by subesokun** [comment]
A recommendation could be to host your own [jspm registry](https://github.com/jspm/registry) and then upload your custom package override there. This way you don't have to add the jspm configuration to the original package. You can easily clone the jspm registry by cloning it into your private gitlab and then adjust your local registry to point to your cloned registry. I think gitlab is also smart enough to auto sync with the original jspm registry. See https://github.com/jspm/jspm-cli/blob/master/docs/registries.md#creating-a-private-jspm-registry

**Comment by subesokun** [comment]
If you've more question please feel free to post them here :) Closing for now.
