### ISSUE TITLE
JSPM loader-files issue when using jspm-git

### ISSUE THREAD

**Issue by mmilbrath** [Orbs/jspm-git#41]
I'm attempting to establish a mirror of GitHub repositories internally leveraging the jspm-git plugin and everything is working well but ran into an issue when JSPM attempts to download the loader-files I get an error that the .../loader-files/systems directories does not exist.

I believe the issue is that the jspm-git plugin expects the directory to exist but doesn't so blows up.  I could probably be fixed on the JSPM side but since the existing/native github repository plugin works seems like this may be the more appropriate place.

A simple fix may be to update the moveRepoToOutDir function to ensure/create the outDir before moving from the temporary location.  Let me know thoughts?

Regards

**Comment by subesokun** [comment]
Hi @mmilbrath, is this a sporadic error or does it always occur? Actually jspm-git is not downloading the loader-files so I'm not exactly sure what's going wrong in your case. As far as I know the loader-files just like the `system.js` are getting directly downloaded via the jspm core, see [here](https://github.com/jspm/jspm-cli/blob/ff46dbcada4236603649344913aa543011dcfbc1/lib/core.js#L303).

Regarding the `moveRepoToOutDir` function, as the `outDir` path gets passed in by jspm I'd expect that this path already exists (up to the parent folder) and if not that should be fixed directly within jspm. I had a look on the Github registry but also there no check gets performed whether the `outDir` exists or not.

Maybe you can give me some more input regarding your issue.

**Comment by mmilbrath** [comment]
Hi @subesokun.   I'm still tracing through all the logic but suspect it is due to the fact that we are also mirroring the GitHub registry internally and overriding the default repo location of https://github.com/jspm/registry.git with the internal mirror.  A snippet of the relevant sections of config and overriding the jspm repo is included below.

You may be right in the the jspm-git plugin should have a reasonable expectation that outDir exists but since it works with the default github registry plugin I thought it may make sense to do within this plugin.  You are in better position to make that determination though.

Below is output without the logic of ensuring outDir exists within the jspm-git plugin.   

Let me know your thoughts...

Regards 

=============
JSPM config

...
    "github": {
      "version": "1.0",
      "baseurl": "http://192.168.99.100:32769/",
      "handler": "jspm-git",
      "remote": "http://192.168.99.100:32769/"
    },
    ...
    "jspm": {
      "handler": "jspm-registry",
      "repo": "http://192.168.99.100:32769/jspm/registry.git",
      "remote": "https://registry.jspm.io"
	}
...


$ jspm dl-loader
     Looking up loader files...
Thu Jun 09 2016 07:57:57 GMT-0400 (Eastern Daylight Time): Error while moving repo to outDir: Error: ENOENT: no such file or directory, mkdir 'C:\Users\mmilbrat
h\AppData\Local\.jspm\loader-files\systemjs'

warn Error on download for github:systemjs/systemjs
     Error: ENOENT: no such file or directory, mkdir '$LOCALAPPDATA\.jspm\loader-files\systemjs'

err

err  Error downloading loader files.

# After creating directory and re-running it works
$  mkdir -p $LOCALAPPDATA/.jspm/loader-files/systemjs
$  jspm dl-loader
     Looking up loader files...
       system.js.map
       system-csp-production.js
       system.js
       system.src.js
       system-csp-production.js.map
       system-polyfills.js
       system-csp-production.src.js
       system-polyfills.src.js
       system-polyfills.js.map

     Using loader versions:
       systemjs@0.19.29
ok   Loader files downloaded successfully

**Comment by subesokun** [comment]
Ah ok, you're completely replacing the github registry against jspm-git. Actually I'm positively surprised that this doesn't cause any other issues beside the one you've mentioned :p

The github registry uses some npm tar package for extracting the files which might be creating the missing intermediate folders. As this will be an easy fix and won't add much logic I'll try to get soon a new release ready.

**Comment by mmilbrath** [comment]
Thanks @subesokun !

**Comment by subesokun** [comment]
Thanks a log for the PR! Just merged it and release the new version :) Sorry for letting you wait.
