### ISSUE TITLE
Error: conq: repository does not exist.

### ISSUE THREAD

**Issue by ajithr** [Orbs/jspm-git#44]
First I created the bitbucket registry using `jspm registry create bitbucket jspm-git` and provided the base url as **ssh://git@bitbucket.org/**. 

Then configured the bitbucket in a folder using `jspm registry config bitbucket`

When I install using `jspm install bitbucket:account/repo.git` it throws the below error.

```
 Looking up bitbucket:account/repo.git

warn Error on lookup for bitbucket:account/repo.git, retrying (1).
     Error: conq: repository does not exist.
     fatal: Could not read from remote repository.

     Please make sure you have the correct access rights
     and the repository exists.

    ...........
    ...........
```

I can checkout the same private repository using below command, but can't install using jspm-git.

`git clone ssh://git@bitbucket.org/account/repo.git`

**Note:** jspm and jspm-git installed with global access.

jspm : 0.16.39
jspm-git : 0.4.5

**Comment by subesokun** [comment]
Hi @ajithr, is `jspm install bitbucket:account/repo` working for you? In case of the jspm install command you've to leave the .git suffix away as it will be appended automatically.

**Comment by ajithr** [comment]
Yep, its working. thanks for the suggestion. :-)
