### ISSUE TITLE
jspm-git bitbucket packageConfigPaths are wrong

### ISSUE THREAD

**Issue by skorlir** [Orbs/jspm-git#47]
When using jspm 0.17.0-beta.22 and jspm-git@beta, setting up bitbucket as a registry like so:

```
$ jspm registry create bitbucket jspm-git
// set it up as ssh://git@bitbucket.org/
```

Creates an entry in the jspm.config.js packageConfigPaths that looks like `bitbucket:*.json`, but because installing bitbucket repos puts them into folders just like GitHub does (eg, `jspm i bitbucket:my-org/my-lib`), this won't resolve dependencies correctly. You need the packageConfigPaths entry to look like GitHub's - ie, `bitbucket:*/*.json` instead of `bitbucket:*.json`.

**Comment by subesokun** [comment]
@skorlir I'll investigate this issue

**Comment by unional** [comment]
second that. I fixed it manually and forgot to file a PR. This behavior exists pre-0.17.0-beta.17

**Comment by atrauzzi** [comment]
Any progress on this?

**Comment by unional** [comment]
I didn't have time to look into it. 😞

**Comment by atrauzzi** [comment]
Does anyone?  Seems like a fairly glaring bug, it basically prevents this from working for anyone who doesn't go digging for this specific ticket.

**Comment by subesokun** [comment]
Patch has been release via v0.5.0-beta.4, sorry for the troubles.
