### ISSUE TITLE
Git version check fails

### ISSUE THREAD

**Issue by pierzakp** [Orbs/jspm-git#52]
Hi,

In git.js in line 50, were script is checking git version and trying to match it using regular expression is failing on command output like `git version 1.10.1.windows.1`.
It is caused because `versionArr = stdout.match(/\d.\d.\d/);` is expecting single digit.

**Comment by NikitaPuza** [comment]
Changing `versionArr = stdout.match(/\d.\d.\d/);` to `versionArr = stdout.match(/\d+\.\d+\.\d+/);` fixed the problem for me.

**Comment by subesokun** [comment]
Sorry totally forgot about this issue :( Once I find some time in the next week's I'll fix it.

**Comment by SeanLS** [comment]
Could you please implement this fix as it starting causing havock for a few people? I am happy to do the fix myself as a contributor should you prefer.

**Comment by subesokun** [comment]
@SeanLS actually the issue has been already fixed long time ago via 80869f055fb6ad45c86a1ea120713c223731b826  ago but I've missed to close this issue. Which version of jspm-git are you using?

**Comment by SeanLS** [comment]
@subesokun Thank you very much. I am not sure at the moment regarding version. I will get back to you.
